### ISSUE TITLE
Locations: The page won't scroll on iPhone

### ISSUE THREAD

**Issue by lanceplaine** [lanceplaine/capnet-pressing#60]
On iPhone the `/locations` page sometimes freeze.

Scenario:

  - Go on the `/index`
  - Reload the page
  - Click on  the "Locations" icon in the navigation
  - Try to scroll the page: the page won't scroll

Note that it is possible to reproduce the bug with the iOS Simulator 

---

It is possible to see the bug in action without having to checkout the project: https://capnet-pressing.herokuapp.com/locations

---

Contributing: Please edit the files in the `src` folder, not the `public` folder. If you use `gulp` it will automatically replicate your changes in the `public` folder.

**Comment by lanceplaine** [comment]
Note that I think it's related to the Google Maps

**Comment by lanceplaine** [comment]
codemill$20

**Comment by biks152207** [comment]
Its working for me.i couldnt recreate this bug

**Comment by lanceplaine** [comment]
@biks152207 has been assigned to this task.

**Comment by lanceplaine** [comment]
@biks152207 has been unassigned from this task.

**Comment by lanceplaine** [comment]
Hi @biks152207,

I tested again the bug and it's definitely here.

Did you tested on an iPhone?

I have iOS 9.2.1 installed.

**Comment by lanceplaine** [comment]
codemill$30

**Comment by lanceplaine** [comment]
A more simple way to reproduce the bug:

  - Go on `/locations`
  - If you try to scroll before the end of page load you can't scroll. If you try to scroll after the page is fully loaded you can scroll.

**Comment by lanceplaine** [comment]
@CrimsonRay has been assigned to this task.

**Comment by acoshift** [comment]
@lanceplaine 
Can you try disable draggable on map ?
I don't have iOS or Mac, so I can't test this.

```js
map = new google.maps.Map(document.getElementById("js_google_map"), {
  center: { lat: 45.764043, lng: 4.835659 },
  zoom: 13,
  draggable: false
});
```

**Comment by lanceplaine** [comment]
Hi @acoshift,

It doesn't solve the issue. I'm still able to have the bug when I switch between the tabs "Index" and "Locations" with the iOS simulator.

**Comment by acoshift** [comment]
@lanceplaine 

Is this bug happen after #10 ?
Can you try delay initMap (by setTimeout ~0-1000) ?

```js
function locationsController ($rootScope, $timeout) {

    // Google Maps
    var map;
    var initMap = function () {
      map = new google.maps.Map(document.getElementById("js_google_map"), {
        center: { lat: 45.764043, lng: 4.835659 },
        zoom: 13
      });
    };
    $timeout(initMap, 200);
```

**Comment by lanceplaine** [comment]
@acoshift: Looks like it was just a CSS issue,

See PR #66

**Comment by CrimsonRay** [comment]
It's a quirky one with `-webkit-overflow-scrolling: touch;`. Transforming the child element "nudges" it and "unstucks" the scroll. Another way would be to just disable the smooth scrolling and use `-webkit-overflow-scrolling: auto;`. Could probably apply the smooth scrolling (`touch;`) using JS after page load, too. Various workarounds, but this is the best I can do without any JS.

If you run into any issues with this, give me a ping here and I'll look into it further. :-)
